only_rules:
  - identifier_name
  - empty_string
  - control_statement
  - colon
  - return_arrow_whitespace
  - syntactic_sugar
  - weak_delegate
  - yoda_condition
  - comma
  - leading_whitespace
  - let_var_whitespace
  - trailing_semicolon
  - opening_brace
  - empty_parentheses_with_trailing_closure
  - fallthrough
  - for_where
  - multiline_parameters
  - unused_optional_binding
  - unused_enumerated
  - unused_closure_parameter
  - unneeded_break_in_switch
  - unavailable_function
  - statement_position
  - large_tuple
  - type_name
  - custom_rules

custom_rules:
  gesture_closure:
    name: "Use weak self in gesture closures"
    message: "Use weak self when creating a gesture closure."
    regex: 'Gesture\s*\(.*\{[^}]*\}'
    severity: error
  no_direct_standard_out_logs:
    name: "Writing log messages directly to standard out is disallowed"
    regex: "(\\bprint|\\bdebugPrint|\\bdump|Swift\\.print|Swift\\.debugPrint|Swift\\-dump)\\s*\\("
    match_kinds:
      - identifier
    message: "Don't commit 'print(...)', 'debugPrint(...), or 'dump(...) as they write to standard out in release."
    severity: warning 

statement_position:
  severity: error

identifier_name:
  min_length:
    warning: 0
    error: 2
  max_length:
    warning: 999
    error: 50

type_name:
  min_length: 2
  max_length: 50

included:
  - GameStop

excluded: # paths to ignore during linting. Takes precedence over included.
  - Pods
  - Carthage
